language: node_js
node_js:
  - '4'
  - '6'
  - '7'

os:
  - linux
  - osx
  
# OSX/NodeJS 4 stalls the CI VM, might reenable it at a later point.
matrix:
  exclude:
    - os: osx
      node_js: '4'
    
before_install:
  - sudo chmod +x ./travis/setup.sh
  - ./travis/setup.sh
before_script:
  - npm install winston@2.3.0
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'

notifications:
  email: false
