language: node_js
node_js:
  - '4'
  - '6'
  - '7'

os:
  - linux
  - osx
    
before_install:
  - ./travis/setup.sh
before_script:
  - npm install winston@2.3.0
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
