language: node_js
node_js:
  - '8'
  - '10'
  - '12'
os:
  - linux
  - osx
before_install:
  - sudo chmod +x ./travis/setup.sh
  - ./travis/setup.sh
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
script:
  - 'npm run test:package'
  - 'npm run test:unit'
  - 'export DEBUG=testing:*'
  - 'npm run test:integration'
notifications:
  email: false
