language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '11'
os:
  - linux
  - osx
allow_failures:
  - os: osx
    node_js: '4'
before_install:
  - sudo chmod +x ./travis/setup.sh
  - ./travis/setup.sh
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - npm install winston@2.3.1
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
notifications:
  email: false
